name: Markdownlint testing

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml
          dot: true
          ignore_files: examples/ignore/*
          ignore_path: examples/.markdownlintignore
          rules: examples/rules/custom.js
